parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\ActivityLogDoctrineListener:
        tags:
            - { name: doctrine.event_subscriber }

    App\Security\UserChecker:
        tags:
            - { name: security.user_checker }

    App\Service\FirebaseAuthService:
        arguments:
            $credentialsPath: "%env(FIREBASE_CREDENTIALS_JSON)%"

    App\Service\PushNotificationService:
        arguments:
            $credentialsPath: "%env(FIREBASE_CREDENTIALS_JSON)%"